### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by chrisdavies71** [trevorblades/gatsby-plugin-apollo#15]
I am unable to get the plugin to install. I have created a new Gatsby site using the CLI which gives me the following package.json file:

`{
  "name": "apollo-test",
  "version": "1.0.0",
  "private": true,
  "description": "apollo-test",
  "author": "@chrisdavies71",
  "keywords": [
    "gatsby"
  ],
  "scripts": {
    "develop": "gatsby develop",
    "start": "gatsby develop",
    "build": "gatsby build",
    "serve": "gatsby serve",
    "clean": "gatsby clean"
  },
  "dependencies": {
    "gatsby": "^4.12.1",
    "gatsby-plugin-sass": "^5.12.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "sass": "^1.51.0"
  }
}`

When I try to add Apollo using the following command:

`npm install gatsby-plugin-apollo @apollo/client graphql`

I get the following error in my console:

`chrisdavies@Chriss-MacBook-Pro apollo-test % npm install gatsby-plugin-apollo @apollo/client graphql
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: apollo-test@1.0.0
npm ERR! Found: graphql-ws@4.9.0
npm ERR! node_modules/graphql-ws
npm ERR!   graphql-ws@"^4.4.1" from @graphql-tools/url-loader@6.10.1
npm ERR!   node_modules/@graphql-tools/url-loader
npm ERR!     @graphql-tools/url-loader@"^6.0.0" from graphql-config@3.4.1
npm ERR!     node_modules/graphql-config
npm ERR!       graphql-config@"^3.0.2" from eslint-plugin-graphql@4.0.0
npm ERR!       node_modules/eslint-plugin-graphql
npm ERR!         eslint-plugin-graphql@"^4.0.0" from gatsby@4.12.1
npm ERR!         node_modules/gatsby
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! @apollo/client@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: graphql-ws@5.8.1
npm ERR! node_modules/graphql-ws
npm ERR!   peerOptional graphql-ws@"^5.5.5" from @apollo/client@3.5.10
npm ERR!   node_modules/@apollo/client
npm ERR!     @apollo/client@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/chrisdavies/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chrisdavies/.npm/_logs/2022-04-26T05_46_18_213Z-debug-0.log
chrisdavies@Chriss-MacBook-Pro apollo-test %`

Node version is: 16.11.1 npm version is: 8.3.2

Any help much appreciated.

Chris

**Comment by chrisdavies71** [comment]
@trevorblades any ideas on where I should be starting with this?

**Comment by ethanwpdev** [comment]
This plugin does not work with Gatsby v4, I tried installing it along with Gatsby and got peer dependency issues.

**Comment by trevorblades** [comment]
This is an issue with NPM v8 and greater. One of Gatsby's dependencies depends on `graphql-ws` at a different version than `@apollo/client`'s optional peer dependency on `graphql-ws`. You can try this out by _only_ installing `@apollo/client` in a Gatsby v4 project using NPM >= 8.

Your best bet is to either use the `--force` flag on your npm install, or `npm i graphql-ws` to stop NPM complaining about an unmet peer dependency.

**Comment by trevorblades** [comment]
You can trace down where this `graphql-ws` dependency comes from in your package-lock.json file.

`gatsby` > `eslint-plugin-graphql` > `graphql-config` > `@graphql-tools/url-loader` > `graphql-ws@4`

The issue is that `graphql-ws@4` is a transitive dependency of `gatsby`, but `@apollo/client` has an optional peer dependency on `graphql-ws@5`. This never used to bother NPM, but since version 8, it seems to think it's a problem.
